---
title: "Introduction to PhenoPath"
author: "Kieran R Campbell"
date: "July 2017"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r load-pacakges}
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(forcats))
# library(phenopath)
```

## Overview of PhenoPath

## Example on simulated data

### Simulating data

We can simulate data via a call to `simulate_phenopath()`:

```{r simulate-data}
set.seed(123L)
devtools::load_all("~/oxford/phenopath/")
sim <- simulate_phenopath()
```

Structure:

```{r sim-structure}
print(str(sim))
```

```{r some-genes, fig.width = 7}
df_gex <- tbl_df(sim$y[,c(1,3,11,13,21,23,31,33)]) %>% 
  mutate(x = factor(sim[['x']]), z = sim[['z']]) %>% 
  gather(gene, expression, -x, -z)

ggplot(df_gex, aes(x = z, y = expression, color = x)) +
  geom_point() +
  facet_wrap(~ gene, nrow = 2) +
  scale_color_brewer(palette = "Set1")
```

```{r pcaing, fig.show = 'hold'}
pca_df <- tbl_df(prcomp(sim$y)$x[,1:2]) %>% 
  mutate(x = factor(sim[['x']]), z = sim[['z']])

ggplot(pca_df, aes(x = PC1, y = PC2, color = x)) +
  geom_point()

ggplot(pca_df, aes(x = PC1, y = PC2, color = z)) +
  geom_point()
```


### Fit PhenoPath model

```{r see-results, cache=TRUE}
fit <- phenopath(sim$y, sim$x, z_init = sim$z,elbo_tol = 1e-6, thin = 40)
```

plot elbo

```{r plot-elbo}
plot_elbo(fit)
```

### Examining results

```{r plot-results, fig.show = 'hold'}
qplot(sim$z, fit$m_z) +
  xlab("True z") + ylab("Phenopath z")
qplot(sim$z, pca_df$PC1) +
  xlab("True z") + ylab("PC1")
```


```{r print-correlation}
cor(sim$z, fit$m_z)
```

df beta

```{r beta-df, fig.width = 5.3}
gene_names <- paste0("gene", seq_len(ncol(fit$m_beta)))
df_beta <- data_frame(beta = fit$m_beta[1,],
                      beta_sd = sqrt(fit$s_beta[1,]),
                      gene = gene_names)
df_beta$gene <- fct_relevel(df_beta$gene, gene_names)

ggplot(df_beta, aes(x = gene, y = beta)) + 
  geom_point() +
  geom_errorbar(aes(ymin = beta - 2 * beta_sd, ymax = beta + 2 * beta_sd)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        axis.title.x = element_blank()) +
  ylab(expression(beta))
```

Sigints

```{r sig-inters, fig.width = 6}
sig_ints <- significant_interactions(fit)
df_beta$is_sig <- sig_ints

ggplot(df_beta, aes(x = gene, y = beta, color = is_sig)) + 
  geom_point() +
  geom_errorbar(aes(ymin = beta - 2 * beta_sd, ymax = beta + 2 * beta_sd)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        axis.title.x = element_blank()) +
  ylab(expression(beta)) +
  scale_color_brewer(palette = "Set2", name = "Significant")
```


## Technical

```{r sessioninfo}
sessionInfo()
```