# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculate_greek_sum <- function(greek, x) {
    .Call('clvm_calculate_greek_sum', PACKAGE = 'clvm', greek, x)
}

update_greek_sum <- function(g, p, greek_sum, greek, new_greek, x) {
    .Call('clvm_update_greek_sum', PACKAGE = 'clvm', g, p, greek_sum, greek, new_greek, x)
}

greek_square_exp <- function(m_g, s_g, x) {
    .Call('clvm_greek_square_exp', PACKAGE = 'clvm', m_g, s_g, x)
}

cavi_update_pst <- function(y, x, m_c, m_mu, s_c, m_alpha, m_beta, s_beta, a_tau, b_tau, q, tau_q) {
    .Call('clvm_cavi_update_pst', PACKAGE = 'clvm', y, x, m_c, m_mu, s_c, m_alpha, m_beta, s_beta, a_tau, b_tau, q, tau_q)
}

cavi_update_mu <- function(y, x, m_t, m_c, m_alpha, m_beta, a_tau, b_tau, tau_mu) {
    .Call('clvm_cavi_update_mu', PACKAGE = 'clvm', y, x, m_t, m_c, m_alpha, m_beta, a_tau, b_tau, tau_mu)
}

cavi_update_c <- function(y, x, m_t, s_t, m_alpha, m_beta, a_tau, b_tau, m_mu, tau_c) {
    .Call('clvm_cavi_update_c', PACKAGE = 'clvm', y, x, m_t, s_t, m_alpha, m_beta, a_tau, b_tau, m_mu, tau_c)
}

cavi_update_tau <- function(y, x, m_t, s_t, m_c, s_c, m_alpha, m_beta, s_alpha, s_beta, m_mu, s_mu, a, b) {
    .Call('clvm_cavi_update_tau', PACKAGE = 'clvm', y, x, m_t, s_t, m_c, s_c, m_alpha, m_beta, s_alpha, s_beta, m_mu, s_mu, a, b)
}

cavi_update_alpha <- function(beta_sum, p, g, y, x, m_t, m_c, m_alpha, m_beta, a_tau, b_tau, m_mu, tau_alpha) {
    .Call('clvm_cavi_update_alpha', PACKAGE = 'clvm', beta_sum, p, g, y, x, m_t, m_c, m_alpha, m_beta, a_tau, b_tau, m_mu, tau_alpha)
}

cavi_update_beta <- function(alpha_sum, p, g, y, x, m_t, s_t, m_c, m_alpha, m_beta, a_tau, b_tau, a_chi, b_chi, m_mu) {
    .Call('clvm_cavi_update_beta', PACKAGE = 'clvm', alpha_sum, p, g, y, x, m_t, s_t, m_c, m_alpha, m_beta, a_tau, b_tau, a_chi, b_chi, m_mu)
}

cavi_update_chi <- function(m_beta_pg, s_beta_pg, a_beta, b_beta) {
    .Call('clvm_cavi_update_chi', PACKAGE = 'clvm', m_beta_pg, s_beta_pg, a_beta, b_beta)
}

calculate_E_log_Y_given_theta <- function(y, x, m_t, s_t, m_c, s_c, m_alpha, s_alpha, m_beta, s_beta, a_tau, b_tau, m_mu, s_mu) {
    .Call('clvm_calculate_E_log_Y_given_theta', PACKAGE = 'clvm', y, x, m_t, s_t, m_c, s_c, m_alpha, s_alpha, m_beta, s_beta, a_tau, b_tau, m_mu, s_mu)
}

calculate_E_log_p <- function(m_t, s_t, m_c, s_c, m_alpha, s_alpha, m_beta, s_beta, a_tau, b_tau, m_mu, s_mu, a_chi, b_chi, q, tau_q, tau_mu, tau_c, a, b, tau_alpha, a_beta, b_beta) {
    .Call('clvm_calculate_E_log_p', PACKAGE = 'clvm', m_t, s_t, m_c, s_c, m_alpha, s_alpha, m_beta, s_beta, a_tau, b_tau, m_mu, s_mu, a_chi, b_chi, q, tau_q, tau_mu, tau_c, a, b, tau_alpha, a_beta, b_beta)
}

calculate_E_log_q <- function(s_t, s_c, s_alpha, s_beta, a_tau, b_tau, s_mu, a_chi, b_chi) {
    .Call('clvm_calculate_E_log_q', PACKAGE = 'clvm', s_t, s_c, s_alpha, s_beta, a_tau, b_tau, s_mu, a_chi, b_chi)
}

calculate_elbo <- function(y, x, m_t, s_t, m_c, s_c, m_alpha, s_alpha, m_beta, s_beta, a_tau, b_tau, a_chi, b_chi, m_mu, s_mu, q, tau_q, tau_mu, tau_c, a, b, tau_alpha, a_beta, b_beta) {
    .Call('clvm_calculate_elbo', PACKAGE = 'clvm', y, x, m_t, s_t, m_c, s_c, m_alpha, s_alpha, m_beta, s_beta, a_tau, b_tau, a_chi, b_chi, m_mu, s_mu, q, tau_q, tau_mu, tau_c, a, b, tau_alpha, a_beta, b_beta)
}

